import { type GetServerSideProps } from "next";
import Head from "next/head";

import { api } from "@/utils/api";
import getSSRHelper from "@/server/api/getSSRHelper";

import Layout from "@/components/layouts/Layout";
import CardColumnsContainer from "@/components/cards-column/CardColumnsContainer";

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const helper = await getSSRHelper(ctx);
  await helper.post.getAll.prefetch();

  return {
    props: {
      trpcState: helper.dehydrate(),
    },
  };
};

const Home = () => {
  const postQuery = api.post.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Pictures</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className="container mx-auto pt-4">
          {postQuery.isLoading && <div>Loading...</div>}
          {postQuery.isSuccess && postQuery.data && <CardColumnsContainer posts={postQuery.data} />}
        </main>
      </Layout>
    </>
  );
};

export default Home;
